### ISSUE TITLE
Death Island -- loading fails for one sample

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/blitz3d_soloud#2]
Hi Mark,

Trying the latest Blitz3D (1.116), I noticed I was getting no thunder after a lightning flash in Hi-Toro/Death Island. Adding this after the sample loading (about a page down in the IDE) shows that thunder2 is '0', so that sample now seems to fail loading:

`DebugLog wind + " " + sea + " " + rain + " " + thunder1 + " " + thunder2 + " " + run + " " + wade`

Would note that if you get thunder, it may be thunder1 playing! Does load in last version of B3D.

Realise possibly just a SoLoud thing you can't do much about -- let me know and I'll try re-jigging the sample in some way.

Doesn't crash, oddly...

**Comment by blitz-research** [comment]
Hmm, weird, txstorm.wav plays OK on the desktop, might be a bug in soloud's wav loader.

Can you try loading/resaving in a random audio app?

**Comment by DruggedBunny** [comment]
OK, re-saved from another program (freeware OcenAudio) and it loads -- so I think it's SoLoud's loader too.

OcenAudio summary before re-saving (note it mentions mp3 encoding, though hex editor shows it's a RIFF WAV file):
![ocenaudio_info_before](https://github.com/user-attachments/assets/1287755b-2692-4f65-a32b-d2ce33fe5078)

OcenAudio summary after re-saving:
![ocenaudio_info_after](https://github.com/user-attachments/assets/9cdc3530-ce16-44de-9773-f8aea72be09a)

Audacity trying to load the 'before' (old) file:
![audacity_before](https://github.com/user-attachments/assets/772fda87-4229-4a4c-976a-bc60b08c69b0)

Files...

[before_after.zip](https://github.com/user-attachments/files/16401846/before_after.zip)

**Comment by blitz-research** [comment]
I've updated the sample but am gonna leave it there for now I think as it seems to be a one off (so far!).

**Comment by DruggedBunny** [comment]
Yeah, just been a dodgy sample I reckon. FMOD must have ignored the apparently-erroneous mp3 flag I guess, and SoLoud just says (correctly) 'wtf'...
